apiVersion: v1
kind: Service
metadata:
  name: object-detector
spec:
  selector:
    app: object-detector
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detector
  labels:
    app: object-detector
spec:
  selector:
    matchLabels:
      app: object-detector
  replicas: 2
  template:
    metadata:
      labels:
        app: object-detector
    spec:
      containers:
      - name: object-detector
        image: quay.io/codait/max-object-detector:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
      tolerations:
      - key: "special"
        operator: "Equal"
        value: "GPU"
        effect: "NoSchedule"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-kubernetes
spec:
  rules:
  - host: 34.132.82.249.nip.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: max-object-detector
            port:
              number: 80

