apiVersion: v1
kind: Service
metadata:
  name: object-detector
spec:
  selector:
    app: object-detector
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detector
  labels:
    app: object-detector
spec:
  selector:
    matchLabels:
      app: object-detector
  replicas: 2
  template:
    metadata:
      labels:
        app: object-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - west
                - east
      containers:
      - name: object-detector
        image: quay.io/codait/max-object-detector:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
---

