apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: caption-generator-mem
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-caption-generator
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80 
