apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: caption-generator
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: max-image-caption-generator-web-app
  targetCPUUtilizationPercentage: 20
