apiVersion: v1
kind: Service
metadata:
  name: image-caption-generator
spec:
  selector:
    app: image-caption-generator
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-caption-generator
  labels:
    app: image-caption-generator
spec:
  selector:
    matchLabels:
      app: image-caption-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: image-caption-generator
    spec:
      containers:
      - name: image-caption-generator
        image: quay.io/codait/max-image-caption-generator:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "50m"
            memory: "300Mi"
          requests:
            cpu: "50m"
            memory: "400Mi"
